// Generated by png2c [(c) Oleg Vaskevich 2013]

#ifndef _overview_H_
#define _overview_H_

extern const unsigned int overview_width;
extern const unsigned int overview_height;
extern const int overview_size;
extern const unsigned short overview[];

#endif

